let shopItemsData = [
  {
    id: "ioytrhndcv",
    name: "Signature Wrap Dress",
    price: 99,
    desc: "Our signature dresses are a wardrobe staple for a reason",
    img: "images/img-2.jpg",
  },
  {
    id: "jfhgbvnscs",
    name: "Olive Branch Dress",
    price: 45,
    desc: "Look effortlessly on-point at all times with our new season day dress",
    img: "images/img-1.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "Classic T-Shirt",
    price: 25,
    desc: "The fashionable and comfortable t-shirt for everyday wear",
    img: "images/img-3.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Dark Blue Hoodie",
    price: 39,
    desc: "This Hoodie is a soft feel and designed in tune with today's fashion",
    img: "images/img-4.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Evening Dress",
    price: 199,
    desc: "Formal dress that elevates your look with timeless elegance",
    img: "images/img-5.jpg",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Denim Jacket",
    price: 89,
    desc: "Denim Jacket with two chest flap pockets and two front side pockets",
    img: "images/img-6.jpg",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "Long Sleeved Top",
    price: 35,
    desc: "Everyone looks like a better version of themselves in this top",
    img: "images/img-7.jpg",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "Camisole",
    price: 19,
    desc: "Choosing from a variety of colours, including white, grey and black",
    img: "images/img-8.jpg",
  },
  {
    id: "cbvxbcvsceldk",
    name: "Flower Shoes",
    price: 185,
    desc: "Elegance is key this season and these shoes are definitely that",
    img: "images/img-9.jpg",
  },
  {
    id: "oiopijmjkhuihb",
    name: "Stiletto Heel",
    price: 105,
    desc: "The ever-classic stiletto heel is updated for the new season",
    img: "images/img-10.jpg",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "Chelsea Boots",
    price: 99,
    desc: "Made with premium Better Leather from a sustainable source",
    img: "images/img-11.jpg",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "leather boots",
    price: 85,
    desc: "For a secure fit and feel over the trails, pull on these trainers",
    img: "images/img-12.jpg",
  },
];
